---
- name: Install MySQL
  apt: 
    name: "{{ item }}"
    update_cache: yes
    cache_valid_time: 3600
    state: present
  become: yes
  with_items:
  - mysql-server
  - mysql-client
  - libmysqlclient-dev
  - python-mysqldb
  notify: Start the MySQL service
